2025-09-18 04:28:01,188 14296 INFO ? odoo: Odoo version 17.0 
2025-09-18 04:28:01,188 14296 INFO ? odoo: Using configuration file at D:\Coding\seriously\learn-odoo\odoo\odoo.conf 
2025-09-18 04:28:01,188 14296 INFO ? odoo: addons paths: ['D:\\Coding\\seriously\\learn-odoo\\odoo\\odoo\\addons', 'd:\\coding\\seriously\\learn-odoo\\odoo\\data\\addons\\17.0', 'd:\\coding\\seriously\\learn-odoo\\odoo\\addons', 'd:\\coding\\seriously\\learn-odoo\\odoo\\custom_addons', 'd:\\coding\\seriously\\learn-odoo\\odoo\\custom_addons\\custom_accounting', 'd:\\coding\\seriously\\learn-odoo\\odoo\\odoo\\addons'] 
2025-09-18 04:28:01,188 14296 INFO ? odoo: database: odoo@localhost:5432 
2025-09-18 04:28:01,378 14296 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe 
2025-09-18 04:28:01,650 14296 WARNING ? odoo.service.server: 'watchdog' module not installed. Code autoreload feature is disabled 
2025-09-18 04:28:01,654 14296 INFO ? odoo.service.server: HTTP service (werkzeug) running on LAPTOP-O0EP5QSP:8069 
2025-09-18 04:28:01,704 14296 INFO ssi_odoo_db odoo.modules.loading: loading 1 modules... 
2025-09-18 04:28:01,704 14296 INFO ssi_odoo_db odoo.modules.loading: 1 modules loaded in 0.00s, 0 queries (+0 extra) 
2025-09-18 04:28:01,720 14296 INFO ssi_odoo_db odoo.modules.loading: updating modules list 
2025-09-18 04:28:01,720 14296 INFO ssi_odoo_db odoo.addons.base.models.ir_module: ALLOW access to module.update_list on [] to user __system__ #1 via n/a 
2025-09-18 04:28:02,955 14296 INFO ssi_odoo_db odoo.addons.base.models.ir_module: ALLOW access to module.button_upgrade on ['TeknoParts Inventory – Spare-part HP'] to user __system__ #1 via n/a 
2025-09-18 04:28:02,955 14296 INFO ssi_odoo_db odoo.addons.base.models.ir_module: ALLOW access to module.update_list on ['TeknoParts Inventory – Spare-part HP'] to user __system__ #1 via n/a 
2025-09-18 04:28:03,582 14296 INFO ssi_odoo_db odoo.addons.base.models.ir_module: ALLOW access to module.button_install on [] to user __system__ #1 via n/a 
2025-09-18 04:28:03,646 14296 INFO ssi_odoo_db odoo.modules.loading: loading 81 modules... 
2025-09-18 04:28:04,899 14296 INFO ssi_odoo_db odoo.modules.loading: Loading module teknoparts_inventory (78/81) 
2025-09-18 04:28:05,267 14296 INFO ssi_odoo_db odoo.modules.registry: module teknoparts_inventory: creating or updating database tables 
2025-09-18 04:28:05,594 14296 INFO ssi_odoo_db odoo.modules.loading: loading teknoparts_inventory/security/security.xml 
2025-09-18 04:28:05,697 14296 INFO ssi_odoo_db odoo.modules.loading: loading teknoparts_inventory/security/ir.model.access.csv 
2025-09-18 04:28:05,741 14296 INFO ssi_odoo_db odoo.modules.loading: loading teknoparts_inventory/security/part_rule.xml 
2025-09-18 04:28:05,760 14296 INFO ssi_odoo_db odoo.modules.loading: loading teknoparts_inventory/security/picking_rule.xml 
2025-09-18 04:28:05,771 14296 INFO ssi_odoo_db odoo.modules.loading: loading teknoparts_inventory/data/sequence.xml 
2025-09-18 04:28:05,776 14296 INFO ssi_odoo_db odoo.modules.loading: loading teknoparts_inventory/wizard/qc_check_wizard.xml 
2025-09-18 04:28:05,785 14296 INFO ssi_odoo_db odoo.modules.loading: loading teknoparts_inventory/wizard/stock_opname_wizard.xml 
2025-09-18 04:28:05,799 14296 INFO ssi_odoo_db odoo.modules.loading: loading teknoparts_inventory/wizard/advanced_print_wizard.xml 
2025-09-18 04:28:05,808 14296 WARNING ssi_odoo_db odoo.modules.loading: Transient module states were reset 
2025-09-18 04:28:05,808 14296 ERROR ssi_odoo_db odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 481, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 229, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 73, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 635, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 680, in convert_xml_import
    doc = etree.parse(xmlfile)
          ^^^^^^^^^^^^^^^^^^^^
  File "src\lxml\etree.pyx", line 3541, in lxml.etree.parse
  File "src\lxml\parser.pxi", line 1900, in lxml.etree._parseDocument
  File "src\lxml\parser.pxi", line 1920, in lxml.etree._parseFilelikeDocument
  File "src\lxml\parser.pxi", line 1814, in lxml.etree._parseDocFromFilelike
  File "src\lxml\parser.pxi", line 1204, in lxml.etree._BaseParser._parseDocFromFilelike
  File "src\lxml\parser.pxi", line 618, in lxml.etree._ParserContext._handleParseResultDoc
  File "src\lxml\parser.pxi", line 728, in lxml.etree._handleParseResult
  File "src\lxml\parser.pxi", line 657, in lxml.etree._raiseParseError
  File "d:\coding\seriously\learn-odoo\odoo\custom_addons\teknoparts_inventory\wizard\advanced_print_wizard.xml", line 69
lxml.etree.XMLSyntaxError: xmlParseEntityRef: no name, line 69, column 56
2025-09-18 04:28:05,810 14296 CRITICAL ssi_odoo_db odoo.service.server: Failed to initialize database `ssi_odoo_db`. 
Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\service\server.py", line 1369, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 481, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 229, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 73, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 635, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 680, in convert_xml_import
    doc = etree.parse(xmlfile)
          ^^^^^^^^^^^^^^^^^^^^
  File "src\lxml\etree.pyx", line 3541, in lxml.etree.parse
  File "src\lxml\parser.pxi", line 1900, in lxml.etree._parseDocument
  File "src\lxml\parser.pxi", line 1920, in lxml.etree._parseFilelikeDocument
  File "src\lxml\parser.pxi", line 1814, in lxml.etree._parseDocFromFilelike
  File "src\lxml\parser.pxi", line 1204, in lxml.etree._BaseParser._parseDocFromFilelike
  File "src\lxml\parser.pxi", line 618, in lxml.etree._ParserContext._handleParseResultDoc
  File "src\lxml\parser.pxi", line 728, in lxml.etree._handleParseResult
  File "src\lxml\parser.pxi", line 657, in lxml.etree._raiseParseError
  File "d:\coding\seriously\learn-odoo\odoo\custom_addons\teknoparts_inventory\wizard\advanced_print_wizard.xml", line 69
lxml.etree.XMLSyntaxError: xmlParseEntityRef: no name, line 69, column 56
2025-09-18 04:28:11,404 14296 INFO ? odoo.modules.loading: loading 1 modules... 
2025-09-18 04:28:11,405 14296 INFO ? odoo.modules.loading: 1 modules loaded in 0.00s, 0 queries (+0 extra) 
2025-09-18 04:28:11,422 14296 INFO ? odoo.modules.loading: loading 81 modules... 
2025-09-18 04:28:11,488 14296 INFO ? odoo.modules.loading: Loading module teknoparts_inventory (78/81) 
2025-09-18 04:28:11,919 14296 INFO ? odoo.modules.registry: module teknoparts_inventory: creating or updating database tables 
2025-09-18 04:28:12,177 14296 INFO ? odoo.modules.loading: loading teknoparts_inventory/security/security.xml 
2025-09-18 04:28:12,254 14296 INFO ? odoo.modules.loading: loading teknoparts_inventory/security/ir.model.access.csv 
2025-09-18 04:28:12,280 14296 INFO ? odoo.modules.loading: loading teknoparts_inventory/security/part_rule.xml 
2025-09-18 04:28:12,291 14296 INFO ? odoo.modules.loading: loading teknoparts_inventory/security/picking_rule.xml 
2025-09-18 04:28:12,298 14296 INFO ? odoo.modules.loading: loading teknoparts_inventory/data/sequence.xml 
2025-09-18 04:28:12,305 14296 INFO ? odoo.modules.loading: loading teknoparts_inventory/wizard/qc_check_wizard.xml 
2025-09-18 04:28:12,318 14296 INFO ? odoo.modules.loading: loading teknoparts_inventory/wizard/stock_opname_wizard.xml 
2025-09-18 04:28:12,320 14296 INFO ? odoo.modules.loading: loading teknoparts_inventory/wizard/advanced_print_wizard.xml 
2025-09-18 04:28:12,342 14296 WARNING ? odoo.modules.loading: Transient module states were reset 
2025-09-18 04:28:12,342 14296 ERROR ? odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\registry.py", line 87, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'ssi_odoo_db'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 481, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 229, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 73, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 635, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 680, in convert_xml_import
    doc = etree.parse(xmlfile)
          ^^^^^^^^^^^^^^^^^^^^
  File "src\lxml\etree.pyx", line 3541, in lxml.etree.parse
  File "src\lxml\parser.pxi", line 1900, in lxml.etree._parseDocument
  File "src\lxml\parser.pxi", line 1920, in lxml.etree._parseFilelikeDocument
  File "src\lxml\parser.pxi", line 1814, in lxml.etree._parseDocFromFilelike
  File "src\lxml\parser.pxi", line 1204, in lxml.etree._BaseParser._parseDocFromFilelike
  File "src\lxml\parser.pxi", line 618, in lxml.etree._ParserContext._handleParseResultDoc
  File "src\lxml\parser.pxi", line 728, in lxml.etree._handleParseResult
  File "src\lxml\parser.pxi", line 657, in lxml.etree._raiseParseError
  File "d:\coding\seriously\learn-odoo\odoo\custom_addons\teknoparts_inventory\wizard\advanced_print_wizard.xml", line 69
lxml.etree.XMLSyntaxError: xmlParseEntityRef: no name, line 69, column 56
2025-09-18 04:28:12,345 14296 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\registry.py", line 87, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'ssi_odoo_db'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\http.py", line 2396, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\http.py", line 1949, in _serve_db
    self.registry = Registry(self.db).check_signaling()
                    ^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\registry.py", line 89, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 481, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 229, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 73, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 635, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 680, in convert_xml_import
    doc = etree.parse(xmlfile)
          ^^^^^^^^^^^^^^^^^^^^
  File "src\lxml\etree.pyx", line 3541, in lxml.etree.parse
  File "src\lxml\parser.pxi", line 1900, in lxml.etree._parseDocument
  File "src\lxml\parser.pxi", line 1920, in lxml.etree._parseFilelikeDocument
  File "src\lxml\parser.pxi", line 1814, in lxml.etree._parseDocFromFilelike
  File "src\lxml\parser.pxi", line 1204, in lxml.etree._BaseParser._parseDocFromFilelike
  File "src\lxml\parser.pxi", line 618, in lxml.etree._ParserContext._handleParseResultDoc
  File "src\lxml\parser.pxi", line 728, in lxml.etree._handleParseResult
  File "src\lxml\parser.pxi", line 657, in lxml.etree._raiseParseError
  File "d:\coding\seriously\learn-odoo\odoo\custom_addons\teknoparts_inventory\wizard\advanced_print_wizard.xml", line 69
lxml.etree.XMLSyntaxError: xmlParseEntityRef: no name, line 69, column 56
2025-09-18 04:28:12,348 14296 INFO ? werkzeug: 127.0.0.1 - - [18/Sep/2025 04:28:12] "GET / HTTP/1.1" 500 - 406 0.254 0.705
2025-09-18 04:28:12,361 14296 INFO ? odoo.modules.loading: loading 1 modules... 
2025-09-18 04:28:12,370 14296 INFO ? odoo.modules.loading: 1 modules loaded in 0.01s, 0 queries (+0 extra) 
2025-09-18 04:28:12,382 14296 INFO ? odoo.modules.loading: loading 81 modules... 
2025-09-18 04:28:12,436 14296 INFO ? odoo.modules.loading: Loading module teknoparts_inventory (78/81) 
2025-09-18 04:28:12,768 14296 INFO ? odoo.modules.registry: module teknoparts_inventory: creating or updating database tables 
2025-09-18 04:28:12,988 14296 INFO ? odoo.modules.loading: loading teknoparts_inventory/security/security.xml 
2025-09-18 04:28:13,070 14296 INFO ? odoo.modules.loading: loading teknoparts_inventory/security/ir.model.access.csv 
2025-09-18 04:28:13,087 14296 INFO ? odoo.modules.loading: loading teknoparts_inventory/security/part_rule.xml 
2025-09-18 04:28:13,087 14296 INFO ? odoo.modules.loading: loading teknoparts_inventory/security/picking_rule.xml 
2025-09-18 04:28:13,109 14296 INFO ? odoo.modules.loading: loading teknoparts_inventory/data/sequence.xml 
2025-09-18 04:28:13,115 14296 INFO ? odoo.modules.loading: loading teknoparts_inventory/wizard/qc_check_wizard.xml 
2025-09-18 04:28:13,127 14296 INFO ? odoo.modules.loading: loading teknoparts_inventory/wizard/stock_opname_wizard.xml 
2025-09-18 04:28:13,142 14296 INFO ? odoo.modules.loading: loading teknoparts_inventory/wizard/advanced_print_wizard.xml 
2025-09-18 04:28:13,151 14296 WARNING ? odoo.modules.loading: Transient module states were reset 
2025-09-18 04:28:13,151 14296 ERROR ? odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\registry.py", line 87, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'ssi_odoo_db'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 481, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 229, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 73, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 635, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 680, in convert_xml_import
    doc = etree.parse(xmlfile)
          ^^^^^^^^^^^^^^^^^^^^
  File "src\lxml\etree.pyx", line 3541, in lxml.etree.parse
  File "src\lxml\parser.pxi", line 1900, in lxml.etree._parseDocument
  File "src\lxml\parser.pxi", line 1920, in lxml.etree._parseFilelikeDocument
  File "src\lxml\parser.pxi", line 1814, in lxml.etree._parseDocFromFilelike
  File "src\lxml\parser.pxi", line 1204, in lxml.etree._BaseParser._parseDocFromFilelike
  File "src\lxml\parser.pxi", line 618, in lxml.etree._ParserContext._handleParseResultDoc
  File "src\lxml\parser.pxi", line 728, in lxml.etree._handleParseResult
  File "src\lxml\parser.pxi", line 657, in lxml.etree._raiseParseError
  File "d:\coding\seriously\learn-odoo\odoo\custom_addons\teknoparts_inventory\wizard\advanced_print_wizard.xml", line 69
lxml.etree.XMLSyntaxError: xmlParseEntityRef: no name, line 69, column 56
2025-09-18 04:28:13,153 14296 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\registry.py", line 87, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'ssi_odoo_db'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\http.py", line 2396, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\http.py", line 1949, in _serve_db
    self.registry = Registry(self.db).check_signaling()
                    ^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\registry.py", line 89, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 481, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 229, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 73, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 635, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 680, in convert_xml_import
    doc = etree.parse(xmlfile)
          ^^^^^^^^^^^^^^^^^^^^
  File "src\lxml\etree.pyx", line 3541, in lxml.etree.parse
  File "src\lxml\parser.pxi", line 1900, in lxml.etree._parseDocument
  File "src\lxml\parser.pxi", line 1920, in lxml.etree._parseFilelikeDocument
  File "src\lxml\parser.pxi", line 1814, in lxml.etree._parseDocFromFilelike
  File "src\lxml\parser.pxi", line 1204, in lxml.etree._BaseParser._parseDocFromFilelike
  File "src\lxml\parser.pxi", line 618, in lxml.etree._ParserContext._handleParseResultDoc
  File "src\lxml\parser.pxi", line 728, in lxml.etree._handleParseResult
  File "src\lxml\parser.pxi", line 657, in lxml.etree._raiseParseError
  File "d:\coding\seriously\learn-odoo\odoo\custom_addons\teknoparts_inventory\wizard\advanced_print_wizard.xml", line 69
lxml.etree.XMLSyntaxError: xmlParseEntityRef: no name, line 69, column 56
2025-09-18 04:28:13,156 14296 INFO ? werkzeug: 127.0.0.1 - - [18/Sep/2025 04:28:13] "GET / HTTP/1.1" 500 - 406 0.242 0.559
2025-09-18 04:28:13,198 14296 INFO ? odoo.modules.loading: loading 1 modules... 
2025-09-18 04:28:13,304 14296 INFO ? odoo.modules.loading: 1 modules loaded in 0.11s, 0 queries (+0 extra) 
2025-09-18 04:28:13,320 14296 INFO ? odoo.modules.loading: loading 81 modules... 
2025-09-18 04:28:13,370 14296 INFO ? odoo.modules.loading: Loading module teknoparts_inventory (78/81) 
2025-09-18 04:28:13,706 14296 INFO ? odoo.modules.registry: module teknoparts_inventory: creating or updating database tables 
2025-09-18 04:28:13,946 14296 INFO ? odoo.modules.loading: loading teknoparts_inventory/security/security.xml 
2025-09-18 04:28:14,018 14296 INFO ? odoo.modules.loading: loading teknoparts_inventory/security/ir.model.access.csv 
2025-09-18 04:28:14,046 14296 INFO ? odoo.modules.loading: loading teknoparts_inventory/security/part_rule.xml 
2025-09-18 04:28:14,055 14296 INFO ? odoo.modules.loading: loading teknoparts_inventory/security/picking_rule.xml 
2025-09-18 04:28:14,063 14296 INFO ? odoo.modules.loading: loading teknoparts_inventory/data/sequence.xml 
2025-09-18 04:28:14,067 14296 INFO ? odoo.modules.loading: loading teknoparts_inventory/wizard/qc_check_wizard.xml 
2025-09-18 04:28:14,078 14296 INFO ? odoo.modules.loading: loading teknoparts_inventory/wizard/stock_opname_wizard.xml 
2025-09-18 04:28:14,094 14296 INFO ? odoo.modules.loading: loading teknoparts_inventory/wizard/advanced_print_wizard.xml 
2025-09-18 04:28:14,103 14296 WARNING ? odoo.modules.loading: Transient module states were reset 
2025-09-18 04:28:14,103 14296 ERROR ? odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\registry.py", line 87, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'ssi_odoo_db'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 481, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 229, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 73, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 635, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 680, in convert_xml_import
    doc = etree.parse(xmlfile)
          ^^^^^^^^^^^^^^^^^^^^
  File "src\lxml\etree.pyx", line 3541, in lxml.etree.parse
  File "src\lxml\parser.pxi", line 1900, in lxml.etree._parseDocument
  File "src\lxml\parser.pxi", line 1920, in lxml.etree._parseFilelikeDocument
  File "src\lxml\parser.pxi", line 1814, in lxml.etree._parseDocFromFilelike
  File "src\lxml\parser.pxi", line 1204, in lxml.etree._BaseParser._parseDocFromFilelike
  File "src\lxml\parser.pxi", line 618, in lxml.etree._ParserContext._handleParseResultDoc
  File "src\lxml\parser.pxi", line 728, in lxml.etree._handleParseResult
  File "src\lxml\parser.pxi", line 657, in lxml.etree._raiseParseError
  File "d:\coding\seriously\learn-odoo\odoo\custom_addons\teknoparts_inventory\wizard\advanced_print_wizard.xml", line 69
lxml.etree.XMLSyntaxError: xmlParseEntityRef: no name, line 69, column 56
2025-09-18 04:28:14,103 14296 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\registry.py", line 87, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'ssi_odoo_db'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\http.py", line 2396, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\http.py", line 1949, in _serve_db
    self.registry = Registry(self.db).check_signaling()
                    ^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\registry.py", line 89, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 481, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 229, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\modules\loading.py", line 73, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 635, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "D:\Coding\seriously\learn-odoo\odoo\odoo\tools\convert.py", line 680, in convert_xml_import
    doc = etree.parse(xmlfile)
          ^^^^^^^^^^^^^^^^^^^^
  File "src\lxml\etree.pyx", line 3541, in lxml.etree.parse
  File "src\lxml\parser.pxi", line 1900, in lxml.etree._parseDocument
  File "src\lxml\parser.pxi", line 1920, in lxml.etree._parseFilelikeDocument
  File "src\lxml\parser.pxi", line 1814, in lxml.etree._parseDocFromFilelike
  File "src\lxml\parser.pxi", line 1204, in lxml.etree._BaseParser._parseDocFromFilelike
  File "src\lxml\parser.pxi", line 618, in lxml.etree._ParserContext._handleParseResultDoc
  File "src\lxml\parser.pxi", line 728, in lxml.etree._handleParseResult
  File "src\lxml\parser.pxi", line 657, in lxml.etree._raiseParseError
  File "d:\coding\seriously\learn-odoo\odoo\custom_addons\teknoparts_inventory\wizard\advanced_print_wizard.xml", line 69
lxml.etree.XMLSyntaxError: xmlParseEntityRef: no name, line 69, column 56
2025-09-18 04:28:14,103 14296 INFO ? werkzeug: 127.0.0.1 - - [18/Sep/2025 04:28:14] "GET /favicon.ico HTTP/1.1" 500 - 406 0.275 0.638
2025-09-18 04:29:46,923 14296 INFO ssi_odoo_db odoo.service.server: Initiating shutdown 
2025-09-18 04:29:46,923 14296 INFO ssi_odoo_db odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2025-09-18 04:29:47,417 14296 INFO ssi_odoo_db odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 3 connections  
